import genaration from '../utils/classname'

export const alertClass = genaration(require('./alert.less'), 'alert')
export const buttonClass = genaration(require('./button.less'), 'button')
export const dropdownClass = genaration(require('./dropdown.less'), 'dropdown')
export const hidableClass = genaration(require('./hidable.less'), 'hidable')
export const listClass = genaration(require('./list.less'), 'list')
export const messageClass = genaration(require('./message.less'), 'message')
export const tableClass = genaration(require('./table.less'), 'table')
export const scrollClass = genaration(require('./scroll.less'), 'scroll')
export const paginationClass = genaration(require('./pagination.less'), 'pagination')
export const breadcrumbClass = genaration(require('./breadcrumb.less'), 'breadcrumb')
export const iconClass = genaration(require('./icon.less'), 'icon')
export const menuClass = genaration(require('./menu.less'), 'menu')
export const checkinputClass = genaration(require('./checkinput.less'), 'check-input')
export const formClass = genaration(require('./form.less'), 'form')
export const inputClass = genaration(require('./form.less'), 'input')
export const selectClass = genaration(require('./select.less'), 'select')
export const modalClass = genaration(require('./modal.less'), 'modal')
