# This is a basic workflow to help you get started with Actions

name: gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "deploy-v2-doc" ]
  pull_request:
    branches: [ "deploy-v2-doc" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.release.tag_name}}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:doc

      - name: Set version directory
        id: set_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DIR_VERSION=$(echo $VERSION | sed 's/\.[^.]*$//')
          echo "VERSION_DIR=./gh-pages/${DIR_VERSION}x" >> $GITHUB_ENV

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.VERSION_DIR }}
